### ISSUE TITLE
supysonic watcher loop

### ISSUE THREAD

**Issue by sentriz** [foosinn/supysonic#2]
Hello, this seems like the best supysonic container I've come across so far (I haven't tried it yet though)
But I just saw this:
https://github.com/foosinn/supysonic/blob/master/init.sh#L42

Is every second an OK interval to be scanning your whole music library for changes? Or does that command do something different? I'm just paranoid about my hard drives getting hammered.

Thank you

**Comment by foosinn** [comment]
The watcher will run as daemon and watch the file system for changes. The sleep 1 is just there to prevent the process from eating CPU if it can't be started.

Thanks for your kind words!
