### ISSUE TITLE
watcher not working

### ISSUE THREAD

**Issue by sentriz** [foosinn/supysonic#3]
hello, sorry for being vague, but the watcher is not working at all. 
but when I `docker exec -t -i supysonic /bin/su supysonic -c supysonic-cli` and do `folder scan Library` it works just fine.
I know there isn't enough information here to find out what's wrong, but are there some sort of logs I can read to find out? `docker logs` doesn't seem to show anything related to scanning. 
btw, I'm using a modified version of your container 
https://github.com/sentriz/supysonic/blob/master/init.sh
(I needed a persistent config, for last.fm) so maybe I've done something stupid?

Thank you very much

EDIT
here is my compose http://termbin.com/fj60

EDIT
I had my music mounted as read only, after making it read and write, the scanner starting working again.
Do you know why that would make a difference?

**Comment by foosinn** [comment]
hey sentriz,

i assume that thats an issue with readonly mounts and inotify. I did also a quick test, works well for me.
